#!/usr/bin/env perl

# TodoTxt Tools
# Copyright (C) 2013 Bram Schoenmakers <me@bramschoenmakers.nl>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use lib '..';
use TodoTxt;
use Depends;

sub usage {
  print STDERR "Usage: todo.sh do TASK#[,TASK#,...]\n";
  exit 1;
}

sub confirmDepsDone {
  print "Also mark subtasks as done? [n] " ;
  my $answer = <STDIN>;

  return $answer =~ /^y(es)?$/i;
}

usage() unless $ARGV[ 1 ] =~ /^\d+(,\d+)*$/;

my $force = $ENV{ 'TODOTXT_FORCE' };

my $filename = $ENV{ 'TODO_DIR' } . "/todo.txt";
TodoTxt::readTodos( $filename );

my @done = split( ',', $ARGV[ 1 ] );
my %done = map { $_ => 1 } @done;

my @todos = map { TodoTxt::getTodo( $_ ) } @done;

my $subTaskExists = grep { TodoTxt::hasTag( $_, 'id' ) } @todos;

if ( $subTaskExists && !$force && confirmDepsDone() ) {
  map { $done{ $_->{ 'num' } } = 1 } TodoTxt::getDependencies( $_ ) foreach @todos;
}

# execute the 'super' do
my $command = sprintf( "%s command do %s", $ENV{ 'TODO_FULL_SH' }, join( ',', keys %done ) );
print `$command`;
